// Common
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DESKTOP_DRAWER = 'CLOSE_DESKTOP_DRAWER';
export const OPEN_DESKTOP_DRAWER = 'OPEN_DESKTOP_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SIDE_BAR_MENU_ITEMS_SUCCESS = 'SIDE_BAR_MENU_ITEMS_SUCCESS';
export const SIDE_BAR_MENU_ITEMS_FAIL = 'SIDE_BAR_MENU_ITEMS_FAIL';
export const OPEN_VIEW_DIALOG = 'OPEN_VIEW_DIALOG';
export const CLOSE_VIEW_DIALOG = 'CLOSE_VIEW_DIALOG';
export const RESET_CONFIRM_PROMPT_DATA = 'RESET_CONFIRM_PROMPT_DATA';
export const RESET_REMARK_PROMPT_DATA = 'RESET_REMARK_PROMPT_DATA';
export const OPEN_VIEW_DIALOG_BOX = 'OPEN_VIEW_DIALOG_BOX';
export const CLOSE_VIEW_DIALOG_BOX = 'CLOSE_VIEW_DIALOG_BOX';

// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_USER_IP = 'GET_USER_IP';
export const SAVE_EXISTING_AUTH_TOKEN = 'SAVE_EXISTING_AUTH_TOKEN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const EXTEND_SESSION = 'EXTEND_SESSION';
export const SAVE_TOKEN_DATA = 'SAVE_TOKEN_DATA';
export const STORE_MULTIPLE_ACCOUNTS = 'STORE_MULTIPLE_ACCOUNTS';
export const UPDATE_BUSINESS_USER = 'UPDATE_BUSINESS_USER';
export const STORE_GEOGRAPHIC_DETAILS = 'STORE_GEOGRAPHIC_DETAILS';
export const STORE_REGION_CODE = 'STORE_REGION_CODE';

// Alerts
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const OPEN_VIEW_BUSINESS_DIALOG = 'OPEN_VIEW_BUSINESS_DIALOG';
export const CLOSE_VIEW_BUSINESS_DIALOG = 'CLOSE_VIEW_BUSINESS_DIALOG';

// Popups
export const SHOW_LOGIN_CONTINUE_POPUP = 'SHOW_LOGIN_CONTINUE_POPUP';
export const HIDE_LOGIN_CONTINUE_POPUP = 'HIDE_LOGIN_CONTINUE_POPUP';
export const SHOW_SESSION_CONTINUE_POPUP = 'SHOW_SESSION_CONTINUE_POP';
export const HIDE_SESSION_CONTINUE_POPUP = 'HIDE_SESSION_CONTINUE_POP';

// Password Management
export const OTP_SENT = 'OTP_SENT';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

// Add Business
export const SAVE_BUSINESS_INFORMATION = 'SAVE_BUSINESS_INFORMATION';

// Add Business - Business Information
export const ADD_COUNTRIES = 'ADD_COUNTRIES';
export const ADD_COMPANY_TYPES = 'ADD_COMPANY_TYPES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_SUB_CATEGORIES = 'ADD_SUB_CATEGORIES';
export const ADD_EMIRATES = 'ADD_EMIRATES';
export const ADD_USERS = 'ADD_USERS';
export const STORE_MOBILE_ACCESS_PROMPT_DATA =
  'STORE_MOBILE_ACCESS_PROMPT_DATA';
export const RESET_MOBILE_ACCESS_PROMPT_DATA =
  'RESET_MOBILE_ACCESS_PROMPT_DATA';

// Add Business - Business Subscription
export const STORE_BUSINESS_SUBSCRIPTION_DATA =
  'STORE_BUSINESS_SUBSCRIPTION_DATA';

// Add Business - Transaction Charges
export const STORE_COMPANY_CURRENCY_LIST = 'STORE_COMPANY_CURRENCY_LIST';
export const ADD_ACQUIRING_BANKS = 'ADD_ACQUIRING_BANKS';
export const ADD_ISSUING_BANKS = 'ADD_ISSUING_BANKS';
export const ADD_ISSUING_BANK_RELATIONSHIP_USERS =
  'ADD_ISSUING_BANK_RELATIONSHIP_USERS';
export const ADD_REGISTRAR_GATEWAYS = 'ADD_REGISTRAR_GATEWAYS';
export const ADD_COMPANY_CURRENCIES = 'ADD_COMPANY_CURRENCIES';
export const ADD_COUNTRY_WISE_TAXES = 'ADD_COUNTRY_WISE_TAXES';
export const STORE_TRANSACTION_CHARGES_TABLE_DATA =
  'STORE_TRANSACTION_CHARGES_TABLE_DATA';
export const STORE_GATEWAY_CHARGES_HISTORY = 'STORE_GATEWAY_CHARGES_HISTORY';

// Add Business - Settlement Charges
export const ADD_SETTLEMENT_BANKS = 'ADD_SETTLEMENT_BANKS';
export const STORE_SETTLEMENT_CHARGES_TABLE_DATA =
  'STORE_SETTLEMENT_CHARGES_TABLE_DATA';

// Add Business - Questionnaire
export const ADD_QUESTIONS = 'ADD_QUESTIONS';

// Manage Business Configurations
export const MANAGE_BUSINESS_DATATABLE = 'MANAGE_BUSINESS_DATATABLE';
export const GET_BUSINESS_CONFIGURATIONS_TO_EXPORT =
  'GET_BUSINESS_CONFIGURATIONS_TO_EXPORT';
export const GET_BUSINESS_INFORMATION = 'GET_BUSINESS_INFORMATION';
export const FLUSH_BUSINESS_CONFIGURATIONS_TO_EXPORT =
  'FLUSH_BUSINESS_CONFIGURATIONS_TO_EXPORT';
export const CLEAR_BUSINESS_INFORMATION = 'CLEAR_BUSINESS_INFORMATION';
export const GET_SALES_REPRESENTATIVE = 'GET_SALES_REPRESENTATIVE';
export const APPROVE_BUSINESS_INFORMATION = 'APPROVE_BUSINESS_INFORMATION';
export const APPROVE_TRANSACTION_CURRENCY = 'APPROVE_TRANSACTION_CURRENCY';
export const APPROVE_BUSINESS_SUBSCRIPTION_DETAILS =
  'APPROVE_BUSINESS_SUBSCRIPTION_DETAILS';
export const APPROVE_TRANSACTION_CHARGES_DETAILS =
  'APPROVE_TRANSACTION_CHARGES_DETAILS';
export const APPROVE_SETTLEMENT_CHARGES_DETAILS =
  'APPROVE_SETTLEMENT_CHARGES_DETAILS';
export const ACTIVATE_BUSINESS = 'ACTIVATE_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const DEACTIVATE_BUSINESS = 'DEACTIVATE_BUSINESS';
export const ASSIGN_TO_SALES_TEAM = 'ASSIGN_TO_SALES_TEAM';
export const OPEN_COMPANY_STATUS_DIALOG = 'OPEN_COMPANY_STATUS_DIALOG';
export const CLOSE_COMPANY_STATUS_DIALOG = 'CLOSE_COMPANY_STATUS_DIALOG';
export const OPEN_KYC_VERIFICATION_DIALOG = 'OPEN_KYC_VERIFICATION_DIALOG';
export const CLOSE_KYC_VERIFICATION_DIALOG = 'CLOSE_KYC_VERIFICATION_DIALOG';
export const FLUSH_KYC_SINGLE_DOCUMENT_DETAILS =
  'FLUSH_KYC_SINGLE_DOCUMENT_DETAILS';
export const FETCH_KYC_SINGLE_DOCUMENT_DETAILS =
  'FETCH_KYC_SINGLE_DOCUMENT_DETAILS';
export const STORE_SAVE_SINGLE_DOCUMENT_FILE =
  'STORE_SAVE_SINGLE_DOCUMENT_FILE';
export const RESET_API_STATUS = 'RESET_API_STATUS';
export const OPEN_CHARGED_SETTINGS_DIALOG = 'OPEN_CHARGED_SETTINGS_DIALOG';
export const CLOSE_CHARGED_SETTINGS_DIALOG = 'CLOSE_CHARGED_SETTINGS_DIALOG';

export const OPEN_FILE_VIEWER_POPUP = 'OPEN_FILE_VIEWER_POPUP';
export const CLOSE_FILE_VIEWER_POPUP = 'CLOSE_FILE_VIEWER_POPUP';
export const FETCH_AML_PROFILES = 'FETCH_AML_PROFILES';
export const OPEN_AML_PROFILES_DIALOG = 'OPEN_AML_PROFILES_DIALOG';
export const CLOSE_AML_PROFILES_DIALOG = 'CLOSE_AML_PROFILES_DIALOG';
export const OPEN_AML_REMARK_DIALOG = 'OPEN_AML_REMARK_DIALOG';
export const CLOSE_AML_REMARK_DIALOG = 'CLOSE_AML_REMARK_DIALOG';
export const RESOLVE_AML_PROFILES = 'RESOLVE_AML_PROFILES';
export const SUBMIT_AML_PROFILE_FEEDBACK = 'SUBMIT_AML_PROFILE_FEEDBACK';
export const UPDATE_KYC_DOCUMENT_STATUS = 'UPDATE_KYC_DOCUMENT_STATUS';

// Types List
export const COMMISSION_TYPE = 'CommissionType';
export const BUSINESS_MODE = 'BusinessMode';
export const CHANNEL_PARTNER = 'ChannelPartner';
export const SERVICE_MODE = 'ServiceMode';
export const CONTACT_TYPE = 'ContactType';
export const DISCOUNTING = 'Discounting';
export const WEB_SUBSCRIPTION = 'WebSubscription';
export const API_SUBSCRIPTION = 'ApiSubscription';
export const CARD_TYPE = 'CardType';
export const SUBSCRIPTION_TYPE = 'SubscriptionType';
export const SUBSCRIPTION_CATEGORY = 'SubscriptionCategory';

// Data Lists
export const STORE_BUSINESS_LIST = 'STORE_BUSINESS_LIST';
export const STORE_CONTACT_LIST = 'STORE_CONTACT_LIST';
export const SAVE_COUNTRY_METADATA_LIST = 'SAVE_COUNTRY_METADATA_LIST';
export const SAVE_BANK_METADATA_LIST = 'SAVE_BANK_METADATA_LIST';
export const STORE_CURRENCY_LIST = 'STORE_CURRENCY_LIST';
export const SAVE_EMIRATES_METADATA_LIST = 'SAVE_EMIRATES_METADATA_LIST';
export const STORE_TYPES = 'STORE_TYPES';
export const STORE_PAY_THROUGH_LIST = 'STORE_PAY_THROUGH_LIST';
export const STORE_MDR_CHARGE_LIST = 'STORE_MDR_CHARGE_LIST';
export const STORE_CURRENCY_BY_PAYMENT_TYPE_LIST =
  'STORE_CURRENCY_BY_PAYMENT_TYPE_LIST';

// Add Contacts
export const STORE_ALL_VENDOR_INFO = 'STORE_ALL_VENDOR_INFO';
export const SAVE_COMPANY_BASIC_INFO = 'SAVE_COMPANY_BASIC_INFO';
export const SAVE_BASIC_INFO_RESPONSE = 'SAVE_BASIC_INFO_RESPONSE';
export const STORE_COMPANY_DETAILS = 'STORE_COMPANY_DETAILS';
export const STORE_BASIC_INFO_RESPONSE = 'STORE_BASIC_INFO_RESPONSE';
export const STORE_INTERNAL_KYC_API_RESPONSE =
  'STORE_INTERNAL_KYC_API_RESPONSE';
export const STORE_EXTERNAL_KYC_API_RESPONSE =
  'STORE_EXTERNAL_KYC_API_RESPONSE';
export const STORE_BANK_ACCOUNT_COUNTRIES = 'STORE_BANK_ACCOUNT_COUNTRIES';
export const STORE_BANK_ACCOUNT_BANKS = 'STORE_BANK_ACCOUNT_BANKS';
export const STORE_BANK_ACCOUNT_TABLE_DATA = 'STORE_BANK_ACCOUNT_TABLE_DATA';

// Business KYC
export const STORE_KYC_DOCUMENT_DETAILS = 'STORE_KYC_DOCUMENT_DETAILS';
export const STORE_KYC_DOCUMENT_FILE = 'STORE_KYC_DOCUMENT_FILE';
export const UNSTORE_KYC_DOCUMENT_FILE = 'UNSTORE_KYC_DOCUMENT_FILE';
export const FETCH_KYC_DOCUMENT_DETAILS = 'FETCH_KYC_DOCUMENT_DETAILS';

// KYC tables
export const STORE_COMPANY_SHARE_HOLDERS = 'STORE_COMPANY_SHARE_HOLDERS';
export const STORE_INDIVIDUAL_SHARE_HOLDERS = 'STORE_INDIVIDUAL_SHARE_HOLDERS';

// Add business user
export const STORE_BUSINESS_USER_BUSINESS_LIST =
  'STORE_BUSINESS_USER_BUSINESS_LIST';
export const STORE_BUSINESS_USER_COUNTRY_LIST =
  'STORE_BUSINESS_USER_COUNTRY_LIST';
export const STORE_BUSINESS_USER_DEPARTMENTS_MAPPED_ROLE =
  'STORE_BUSINESS_USER_DEPARTMENTS_MAPPED_ROLE';
export const STORE_BUSINESS_USER_DATA = 'STORE_BUSINESS_USER_DATA';

// Manage business user
export const STORE_BUSINESS_USER_LIST = 'STORE_BUSINESS_USER_LIST';
export const STORE_BUSINESS_USER_LIST_EXPORT =
  'STORE_BUSINESS_USER_LIST_EXPORT';

// Add bulk payments configuration
export const STORE_COMPANY_FILE_SETTINGS = 'STORE_COMPANY_FILE_SETTINGS';

// Gateway management
export const STORE_CHANNEL_PARTNER_REGISTRARS =
  'STORE_CHANNEL_PARTNER_REGISTRARS';

export const STORE_CHANNEL_PARTNER_CHARGE_TYPES =
  'STORE_CHANNEL_PARTNER_CHARGE_TYPES';

export const STORE_CHANNEL_PARTNER_CHARGE_BANKS =
  'STORE_CHANNEL_PARTNER_CHARGE_BANKS';

export const STORE_CHANNEL_PARTNER_PROCESSING_TYPES =
  'STORE_CHANNEL_PARTNER_PROCESSING_TYPES';

export const STORE_CHANNEL_PARTNER_FETCHED_FORM_DATA =
  'STORE_CHANNEL_PARTNER_FETCHED_FORM_DATA';

export const STORE_CHANNEL_PARTNER_LIST_EXPORT =
  'STORE_CHANNEL_PARTNER_LIST_EXPORT';
export const STORE_CHANNEL_PARTNER_LIST = 'STORE_CHANNEL_PARTNER_LIST';
export const STORE_ALL_REGISTRAR_TYPES = 'STORE_ALL_REGISTRAR_TYPES';
export const STORE_CAHNNEL_PARTNER_CARD_TYPES =
  'STORE_CAHNNEL_PARTNER_CARD_TYPES';

export const STORE_GATEWAY_ROW_DATA_EXPORT = 'STORE_GATEWAY_ROW_DATA_EXPORT';

// Add Incidents
export const STORE_SYSTEM_MODULES = 'STORE_SYSTEM_MODULES';
export const STORE_INCIDENT = 'STORE_INCIDENT';
// Manage Incidents (audit)
export const STORE_INCIDENTS_EXPORT = 'STORE_INCIDENTS_EXPORT';
export const STORE_INCIDENTS = 'STORE_INCIDENTS';
export const STORE_EVENT_LOGS_EXPORT = 'STORE_EVENT_LOGS_EXPORT';
export const STORE_EVENT_LOGS = 'STORE_EVENT_LOGS';
export const OPEN_VIEW_INCIDENT_DIALOG = 'OPEN_VIEW_INCIDENT_DIALOG';
export const CLOSE_VIEW_INCIDENT_DIALOG = 'CLOSE_VIEW_INCIDENT_DIALOG';

// Add User
export const STORE_USER_COUNTRY_LIST = 'STORE_USER_COUNTRY_LIST';
export const STORE_USER_CHANNEL_PARTNER_LIST =
  'STORE_USER_CHANNEL_PARTNER_LIST';
export const STORE_USER_DEPARTMENTS_MAPPED_ROLE =
  'STORE_USER_DEPARTMENTS_MAPPED_ROLE';
export const STORE_USER_DATA = 'STORE_USER_DATA';

// Manage users
export const STORE_ALL_DEPARTMENTS_MAPPED_ROLES =
  'STORE_ALL_DEPARTMENTS_MAPPED_ROLES';
export const STORE_MANAGE_USER_LIST = 'STORE_MANAGE_USER_LIST';
export const STORE_MANAGE_USER_LIST_EXPORT = 'STORE_MANAGE_USER_LIST_EXPORT';

// Settings
// Promo Banner
export const STORE_PROMO_CODE_DATA = 'STORE_PROMO_CODE_DATA';

// Approve Reject Minimum Charges
export const STORE_BUSINESS_DETAILS = 'STORE_BUSINESS_DETAILS';

// Account Settings: Transaction Charges
export const STORE_BUSINESS_TRANSACTION_CHARGES =
  'STORE_BUSINESS_TRANSACTION_CHARGES';

// Account Settings: Manage Workflow
export const STORE_APPROVAL_WORKFLOW_LIST = 'STORE_APPROVAL_WORKFLOW_LIST';
export const STORE_LIST_LIMIT_WORKFLOW = 'STORE_LIST_LIMIT_WORKFLOW';
export const STORE_WORKFLOW_PAYMENT_TYPES = 'STORE_WORKFLOW_PAYMENT_TYPES';
export const STORE_BIND_LIMITS = 'STORE_BIND_LIMITS';
export const STORE_BIND_USER_ROLES = 'STORE_BIND_USER_ROLES';
export const SAVE_EDIT_LIMIT_WORKFLOW = 'SAVE_EDIT_LIMIT_WORKFLOW';

// Edit user - Profile
export const STORE_PROFILE_USER_DATA = 'STORE_PROFILE_USER_DATA';

// Change Password
export const STORE_PROFILE_SETTINGS_CURRENT_PASSWORD =
  'STORE_PROFILE_SETTINGS_CURRENT_PASSWORD';

// Reports
export const STORE_COLLECTIONS_REPORTS_STATUS_CODES =
  'STORE_COLLECTIONS_REPORTS_STATUS_CODES';
export const OPEN_DOWNLOAD_ATTACHMENT_DIALOG =
  'OPEN_DOWNLOAD_ATTACHMENT_DIALOG';
export const CLOSE_DOWNLOAD_ATTACHMENT_DIALOG =
  'CLOSE_DOWNLOAD_ATTACHMENT_DIALOG';
export const STORE_PAYMENTS_REPORTS_STATUS_CODES =
  'STORE_PAYMENTS_REPORTS_STATUS_CODES';
export const STORE_VENDOR_PAYMENTS_REPORTS_STATUS_CODES =
  'STORE_VENDOR_PAYMENTS_REPORTS_STATUS_CODES';
export const STORE_GATEWAY_REPORTS_STATUS_CODES =
  'STORE_GATEWAY_REPORTS_STATUS_CODES';
export const STORE_SETTLEMENT_REPORTS_STATUS_CODES =
  'STORE_SETTLEMENT_REPORTS_STATUS_CODES';
export const STORE_PAYMENT_RECEIVED_REPORT = 'STORE_PAYMENT_RECEIVED_REPORT';
export const STORE_MAKE_PAYMENTS_REPORT = 'STORE_MAKE_PAYMENTS_REPORT';
export const STORE_GATEWAY_TRANSACTION_BUSINESS_REPORT =
  'STORE_GATEWAY_TRANSACTION_BUSINESS_REPORT';
export const STORE_BUSINESS_SUBSCRIPTION_REPORT =
  'STORE_BUSINESS_SUBSCRIPTION_REPORT';
export const STORE_ACCOUNT_BALANCE_HISTORY_REPORT =
  'STORE_ACCOUNT_BALANCE_HISTORY_REPORT';
export const STORE_VENDOR_SUBSCRIPTION_REPORT =
  'STORE_VENDOR_SUBSCRIPTION_REPORT';
export const STORE_SETTLEMENT_TRANSACTION_REPORT =
  'STORE_SETTLEMENT_TRANSACTION_REPORT';
export const STORE_RECEIVED_PAYMENT_VIEW_SUMMARY_REPORT =
  'STORE_RECEIVED_PAYMENT_VIEW_SUMMARY_REPORT';
export const STORE_MAKE_PAYMENT_HISTORY_GRID =
  'STORE_MAKE_PAYMENT_HISTORY_GRID';
export const STORE_INVOICE_ATTACHMENT = 'STORE_INVOICE_ATTACHMENT';
export const FETCH_VENDORS_BY_COMPANY = 'FETCH_VENDORS_BY_COMPANY';
export const STORE_DISCOUNTING_REPORTS = 'STORE_DISCOUNTING_REPORTS';
export const STORE_MANAGE_CONTRACTS = 'STORE_MANAGE_CONTRACTS';
export const STORE_PAYMENT_RECEIVED_VENDOR_REPORTS =
  'STORE_PAYMEMT_RECEIVED_VENDOR_REPORTS';
export const STORE_RENT_COLLECTION_REPORTS = 'STORE_RENT_COLLECTION_REPORTS';

export const STORE_PAYMENT_RECEIVED_REPORT_EXPORT =
  'STORE_PAYMENT_RECEIVED_REPORT_EXPORT';
export const STORE_MAKE_PAYMENTS_REPORT_EXPORT =
  'STORE_MAKE_PAYMENTS_REPORT_EXPORT';
export const STORE_GATEWAY_TRANSACTION_BUSINESS_REPORT_EXPORT =
  'STORE_GATEWAY_TRANSACTION_BUSINESS_REPORT_EXPORT';
export const STORE_BUSINESS_SUBSCRIPTION_REPORT_EXPORT =
  'STORE_BUSINESS_SUBSCRIPTION_REPORT_EXPORT';
export const STORE_ACCOUNT_BALANCE_HISTORY_REPORT_EXPORT =
  'STORE_ACCOUNT_BALANCE_HISTORY_REPORT_EXPORT';
export const STORE_VENDOR_SUBSCRIPTION_REPORT_EXPORT =
  'STORE_VENDOR_SUBSCRIPTION_REPORT_EXPORT';
export const STORE_SETTLEMENT_TRANSACTION_REPORT_EXPORT =
  'STORE_SETTLEMENT_TRANSACTION_REPORT_EXPORT';
export const STORE_MAKE_PAYMENT_HISTORY = 'STORE_MAKE_PAYMENT_HISTORY';

// TAX PAYMENTS
export const STORE_TAX_PAYMENT_REPORT = 'STORE_TAX_PAYMENT_REPORT';
// REGISTERED BUSINESS
export const STORE_REGISTERED_BUSINESS_REPORT =
  'STORE_REGISTERED_BUSINESS_REPORT';
export const STORE_GIBAN_DETAILS = 'STORE_GIBAN_DETAILS';

// Bulk configurations
export const STORE_DESTINATION_FIELDS = 'STORE_DESTINATION_FIELDS';
export const STORE_BULK_CONFIGURATION_LIST = 'STORE_BULK_CONFIGURATION_LIST';
export const STORE_BULK_CONFIGURATION_LIST_EXPORT =
  'STORE_BULK_CONFIGURATION_LIST_EXPORT';

// Cards
export const STORE_CARD_TYPE = 'STORE_CARD_TYPE';
export const STORE_ISSUING_BANKS_FOR_CARDS = 'STORE_ISSUING_BANKS_FOR_CARDS';
export const STORE_CARD_CURRENCY = 'STORE_CARD_CURRENCY';
export const STORE_CARD_LIST_EXPORT = 'STORE_CARD_LIST_EXPORT';
export const STORE_CARD_LIST = 'STORE_CARD_LIST';

// Manage business user
export const STORE_ALL_BUSINESS_DEPARTMENTS_ROLES =
  'STORE_ALL_BUSINESS_DEPARTMENTS_ROLES';

// Manage bank account
export const STORE_ALL_BANK_ACCOUNT_LIST_EXPORT =
  'STORE_ALL_BANK_ACCOUNT_LIST_EXPORT';
export const STORE_ALL_BANK_ACCOUNT_LIST = 'STORE_ALL_BANK_ACCOUNT_LIST';

// Manage contacts
export const STORE_COMPANIES = 'STORE_COMPANIES';
export const STORE_CONTACT_TYPES = 'STORE_CONTACT_TYPES';
export const STORE_MANAGE_CONTACT_LIST = 'STORE_MANAGE_CONTACT_LIST';
export const STORE_MANAGE_CONTACT_EXPORT = 'STORE_MANAGE_CONTACT_EXPORT';

export const OPEN_VIEW_COLLECTION_DIALOG = 'OPEN_VIEW_COLLECTION_DIALOG';
export const CLOSE_VIEW_COLLECTION_DIALOG = 'CLOSE_VIEW_COLLECTION_DIALOG';

export const OPEN_VIEW_PAYMENT_DIALOG = 'OPEN_VIEW_PAYMENT_DIALOG';
export const CLOSE_VIEW_PAYMENT_DIALOG = 'CLOSE_VIEW_PAYMENT_DIALOG';

export const STORE_VENDOR_VIEW_INFO = 'STORE_VENDOR_VIEW_INFO';
export const OPEN_VIEW_GATEWAY_SUMMARY_DIALOG =
  'OPEN_VIEW_GATEWAY_SUMMARY_DIALOG';
export const CLOSE_VIEW_GATEWAY_SUMMARY_DIALOG =
  'CLOSE_VIEW_GATEWAY_SUMMARY_DIALOG';

export const OPEN_MANAGE_USER_STATUS_DIALOG = 'OPEN_MANAGE_USER_STATUS_DIALOG';
export const CLOSE_MANAGE_USER_STATUS_DIALOG =
  'CLOSE_MANAGE_USER_STATUS_DIALOG';

// Dashboard

export const STORE_DASHBOARD_SETTLEMENT_TRANSACTIONS =
  'STORE_DASHBOARD_SETTLEMENT_TRANSACTIONS';
export const STORE_PROFILE_MENU_DETAILS = 'STORE_PROFILE_MENU_DETAILS';
export const STORE_DASHBOARD_QUICK_LINKS = 'STORE_DASHBOARD_QUICK_LINKS';
export const STORE_DASHBOARD_GRAPH_DATA = 'STORE_DASHBOARD_GRAPH_DATA';
export const OPEN_MANAGE_PAYMENT_GATEWAY_STATUS_DIALOG =
  'OPEN_MANAGE_PAYMENT_GATEWAY_STATUS_DIALOG';
export const CLOSE_MANAGE_PAYMENT_GATEWAY_STATUS_DIALOG =
  'CLOSE_MANAGE_PAYMENT_GATEWAY_STATUS_DIALOG';

export const OPEN_SETTLEMENT_BANK_ACCOUNT_DELETE_DIALOG =
  'OPEN_SETTLEMENT_BANK_ACCOUNT_DELETE_DIALOG';
export const CLOSE_SETTLEMENT_BANK_ACCOUNT_DELETE_DIALOG =
  'CLOSE_SETTLEMENT_BANK_ACCOUNT_DELETE_DIALOG';

export const OPEN_BULK_PAYMENT_DELETE_DIALOG =
  'OPEN_BULK_PAYMENT_DELETE_DIALOG';
export const CLOSE_BULK_PAYMENT_DELETE_DIALOG =
  'CLOSE_BULK_PAYMENT_DELETE_DIALOG';
export const OPEN_MANAGE_CARD_STATUS_DIALOG = 'OPEN_MANAGE_CARD_STATUS_DIALOG';
export const CLOSE_MANAGE_CARD_STATUS_DIALOG =
  'CLOSE_MANAGE_CARD_STATUS_DIALOG';

// manage contacts
export const OPEN_DEACTIVATE_VENDOR_DIALOG = '  OPEN_DEACTIVATE_VENDOR_DIALOG';
export const CLOSE_DEACTIVATE_VENDOR_DIALOG =
  '  CLOSE_DEACTIVATE_VENDOR_DIALOG';
export const OPEN_VIEW_VENDOR_DIALOG = '  OPEN_VIEW_VENDOR_DIALOG';
export const CLOSE_VIEW_VENDOR_DIALOG = '  CLOSE_VIEW_VENDOR_DIALOG';
export const OPEN_DELETE_VENDOR_DIALOG = '  OPEN_DELETE_VENDOR_DIALOG';
export const CLOSE_DELETE_VENDOR_DIALOG = '  CLOSE_DELETE_VENDOR_DIALOG';
export const OPEN_APPROVE_REJECT_VENDOR_MODAL =
  '  OPEN_APPROVE_REJECT_VENDOR_MODAL';
export const CLOSE_APPROVE_REJECT_VENDOR_MODAL =
  '  CLOSE_APPROVE_REJECT_VENDOR_MODAL';

// Export Excel/CSV Files from Filters
export const GET_FILES_TO_EXPORT = 'GET_FILES_TO_EXPORT';
export const FLUSH_EXPORT_FILES = 'FLUSH_EXPORT_FILES';

// Common dropdown
export const STORE_VENDOR_LIST = 'STORE_VENDOR_LIST';
export const STORE_PAYMENT_TYPES = 'STORE_PAYMENT_TYPES';
export const STORE_STATUS_CODES = 'STORE_STATUS_CODES';

// Data Table Information
export const STORE_DATA_TABLE_INFORMATION = 'STORE_DATA_TABLE_INFORMATION';
export const STORE_REGISTRAR_MASTER = 'STORE_REGISTRAR_MASTER';

// VENDOR USER
// PAYMENTS (Made Payments)
export const STORE_MADE_PAYMENTS_REPORT = 'STORE_MADE_PAYMENTS_REPORT';

// Checkout
export const STORE_PAYMENT_CHARGES = 'STORE_PAYMENT_CHARGES';

// Pending Approval
export const STORE_PENDING_APPROVAL = 'STORE_PENDING_APPROVAL';
export const STORE_SENDER_RECEIVED_REQUEST = 'STORE_SENDER_RECEIVED_REQUEST';
export const STORE_VENDOR_PAYMENTS_MODES = 'STORE_VENDOR_PAYMENTS_MODES';
export const STORE_VENDOR_PAYMENT_THROUGH = 'STORE_VENDOR_PAYMENT_THROUGH';

// CONTACT ALL ADMIN USER
// Business Settings
export const STORE_BUSINESS_SUBSCRIPTION_PLAN_DETAILS =
  'STORE_BUSINESS_SUBSCRIPTION_PLAN_DETAILS';
export const STORE_BUSINESS_SUBSCRIPTION_PLAN_LIST =
  'STORE_BUSINESS_SUBSCRIPTION_PLAN_LIST';
export const STORE_INVOICE_DATA_FOR_SUBSCRIPTIONS =
  'STORE_INVOICE_DATA_FOR_SUBSCRIPTIONS';

// Make a payment
export const STORE_MAKE_A_PAYMENT_TABLE_DATA =
  'STORE_MAKE_A_PAYMENT_TABLE_DATA';
export const STORE_PAY_FROM_TYPES = 'STORE_PAY_FROM_TYPES';

export const STORE_PAYMENT_EDIT_DATA = 'STORE_PAYMENT_EDIT_DATA';

export const FLUSH_PAYMENT_EDIT_DATA = 'FLUSH_PAYMENT_EDIT_DATA';
//Manage GIBAN - Business List
export const STORE_GIBAN_BUSINESS = 'STORE_GIBAN_BUSINESS';
export const OPEN_VIEW_GIBAN_DIALOG = 'OPEN_VIEW_GIBAN_DIALOG';
export const CLOSE_VIEW_GIBAN_DIALOG = 'CLOSE_VIEW_GIBAN_DIALOG';

// Pending Approvals
export const STORE_PENDING_APPROVALS = 'STORE_PENDING_APPROVALS';

// View Payment Summary Action
export const STORE_PAYMENT_SUMMARY_HISTORY = 'STORE_PAYMENT_SUMMARY_HISTORY';
export const STORE_PAYMENT_SUMMARY_HISTORY_GRID =
  'STORE_PAYMENT_SUMMARY_HISTORY_GRID';

// PAYMENT APPROVALS - VAT PAYMENTS
export const STORE_VAT_PAYMENTS = 'STORE_VAT_PAYMENTS';
export const STORE_PROCESS_APTRANSACTIONS = 'STORE_PROCESS_APTRANSACTIONS';
export const OPEN_APPROVE_VAT_PAYMENT_DIALOG =
  'OPEN_APPROVE_VAT_PAYMENT_DIALOG';
export const CLOSE_APPROVE_VAT_PAYMENT_DIALOG =
  'CLOSE_APPROVE_VAT_PAYMENT_DIALOG';

// PAYMENTS - REQUESTS RECEIVED
export const STORE_REQUESTS_RECEIVED = 'STORE_REQUESTS_RECEIVED';
export const STORE_CONFIRM_RECEIVED_REQUESTS =
  'STORE_CONFIRM_RECEIVED_REQUESTS';
export const STORE_COMPANY_BALANCE = 'STORE_COMPANY_BALANCE';
export const STORE_SENDER_REQUESTS_RECEIVED = 'STORE_SENDER_REQUESTS_RECEIVED';
export const STORE_SEARCH_BUSINESS = 'STORE_SEARCH_BUSINESS';

// Sales - Track Collections
export const STORE_PENDING_REQUESTS = 'STORE_PENDING_REQUESTS';
export const STORE_PENDING_VENDOR_PAYMENTS = 'STORE_PENDING_VENDOR_PAYMENTS';

// refresh table data flag
export const SET_TABLE_REFRESH_FLAG = 'SET_TABLE_REFRESH_FLAG';
export const UNSET_TABLE_REFRESH_FLAG = 'UNSET_TABLE_REFRESH_FLAG';

// bulk contact
export const STORE_BULK_CONTACT_TABLE_DATA = 'STORE_BULK_CONTACT_TABLE_DATA';
export const CLEAR_BULK_CONTACT_TABLE_DATA = 'CLEAR_BULK_CONTACT_TABLE_DATA';

// Settlements
export const SEARCH_ALL_BUSINESS = 'SEARCH_ALL_BUSINESS';
export const STORE_COLLECTION_PAYMENTS = 'STORE_COLLECTION_PAYMENTS';
export const STORE_PAYABLE_PAYMENTS = 'STORE_PAYABLE_PAYMENTS';
export const STORE_TAXABLE_PAYMENTS = 'STORE_TAXABLE_PAYMENTS';
export const STORE_SETTLEMENT_TRANSACTION_VIEW_HISTORY =
  'STORE_SETTLEMENT_TRANSACTION_VIEW_HISTORY';
export const OPEN_VIEW_SETTLEMENT_DIALOG = 'OPEN_VIEW_SETTLEMENT_DIALOG';
export const CLOSE_VIEW_SETTLEMENT_DIALOG = 'CLOSE_VIEW_SETTLEMENT_DIALOG';
export const SAVE_USER_BASIC_INFORMATION = 'SAVE_USER_BASIC_INFORMATION';
export const REMOVE_INVOICE_DATA_FOR_SUBSCRIPTIONS =
  'REMOVE_INVOICE_DATA_FOR_SUBSCRIPTIONS';
export const GET_CONNECTION_REQUESTS = 'GET_CONNECTION_REQUESTS';

export const FETCH_TERMS_AND_POLICIES = 'FETCH_TERMS_AND_POLICIES';
export const ACCEPT_TERMS_AND_POLICIES = 'ACCEPT_TERMS_AND_POLICIES';
export const UPDATE_TERMS_AND_POLICY = 'UPDATE_TERMS_AND_POLICY';

// Rent Collection
export const STORE_REGISTERED_PROPERTY_DATA = 'STORE_REGISTERED_PROPERTY_DATA';
export const STORE_TRACK_RENT_COLLECTIONS_DATA =
  'STORE_TRACK_RENT_COLLECTIONS_DATA';

// Rent Payment
export const STORE_TENANT_MANAGE_PROPERTY = 'STORE_TENANT_MANAGE_PROPERTY';
export const STORE_TENANT_REQUEST_RECEIVED = 'STORE_TENANT_REQUEST_RECEIVED';
export const STORE_TENANT_TRACK_RENT_COLLECTION =
  'STORE_TENANT_TRACK_RENT_COLLECTION';

export const VIEW_SAMPLE_FILE = 'VIEW_SAMPLE_FILE';
